import { eventGroups } from "./events";
import { ensembleGroups, mainNavigation, siteConfig } from "./site-config";

export type CopyMap = Record<string, string>;

export const sharedContentDefaults = {
  siteConfig,
  mainNavigation,
  ensembleGroups,
  eventGroups,
  footer: {
    brand: "Halka",
    tagline: "Od 1948 roku tańczymy razem",
    longTagline: "Pieśń. Taniec. Pokolenia.",
    copyrightShort: "ZPiT Halka",
    copyrightLong: "Zespół Pieśni i Tańca Halka w Lublińcu",
    logoAlt: "Logo Zespołu Pieśni i Tańca Halka",
  },
  header: {
    brand: "Halka",
    brandTop: "Zespół Pieśni i Tańca",
    city: "Lubliniec",
    contactLabel: "Kontakt",
    navigationLabel: "Główna nawigacja",
    mobileNavigationLabel: "Menu mobilne",
    openMenuLabel: "Otwórz menu",
    closeMenuLabel: "Zamknij menu",
    homeAriaLabel: "Halka — przejdź na początek strony",
    pageAriaLabel: "Halka — strona główna",
  },
};

export const homeCopyDefaults: CopyMap = {
  "meta.title": "Zespół Pieśni i Tańca Halka | Lubliniec",
  "meta.description": "Zespół Pieśni i Tańca Halka z Lublińca. Dołącz do jednej z czterech grup albo zaproś zespół na swoje wydarzenie.",
  "skipLabel": "Przejdź do głównej treści",
  "hero.eyebrow": "Tu tradycja żyje",
  "hero.title": "Od 1948 roku",
  "hero.titleAccent": "tańczymy razem.",
  "hero.lead": "Cztery grupy i wiele pokoleń wspólnie pielęgnują śląskie korzenie na scenach w całej Polsce.",
  "hero.primaryCta": "Dołącz do Halki",
  "hero.secondaryCta": "Zaproś nas na wydarzenie",
  "hero.proofLabel": "Najważniejsze informacje o zespole",
  "hero.proof1Title": "Historia",
  "hero.proof1Value": "od 1948",
  "hero.proof2Title": "Zespół",
  "hero.proof2Value": "4 grupy",
  "hero.proof3Title": "Nabór",
  "hero.proof3Value": "cały rok",
  "hero.ariaLabel": "Hero strony głównej",
  "hero.imageAlt": "Tancerka Halki widziana z góry podczas obrotu",
  "hero.imageLabel": "Halka w ruchu",
  "hero.imageCaption": "Tradycja, którą tworzymy dziś.",
  "join.eyebrow": "Nabór otwarty przez cały rok",
  "join.title": "Znajdź swoje miejsce",
  "join.titleAccent": "w Halce.",
  "join.signalLabel": "Cztery grupy, jeden zespół",
  "join.groupWord": "grupy.",
  "join.teamWord": "jeden zespół.",
  "join.fact1": "od 6 lat",
  "join.fact2": "bez przesłuchań",
  "join.fact3": "zajęcia darmowe",
  "join.groupCta": "Poznaj grupę",
  "events.eyebrow": "Najbliższe występy",
  "events.title": "Spotkajmy się pod sceną.",
  "events.cta": "Wszystkie wydarzenia",
  "events.empty": "Nowe terminy występów pojawią się tutaj po ich potwierdzeniu.",
  "events.monthShort": "STY|LUT|MAR|KWI|MAJ|CZE|LIP|SIE|WRZ|PAŹ|LIS|GRU",
  "gallery.railLabel": "Najnowsze galerie. Przewiń poziomo, aby zobaczyć kolejne wydarzenie.",
  "gallery.controlsLabel": "Sterowanie galerią",
  "gallery.previous": "Poprzednie wydarzenie",
  "gallery.next": "Następne wydarzenie",
  "gallery.eyebrow": "Halka na scenie",
  "gallery.title": "Zobacz nas",
  "gallery.titleAccent": "w ruchu.",
  "gallery.lead": "Sceny, festiwale i spotkania, podczas których tworzymy wspólną opowieść. Każdy występ to inna scena, publiczność i emocje, które zostają z nami na długo.",
  "gallery.albumCtaLabel": "Zobacz cały album",
  "gallery.eventLabel": "Wydarzenie",
  "offer.eyebrow": "Dla organizatorów",
  "offer.title": "Zaproś Halkę.",
  "offer.lead": "Możemy przygotować pełną suitę, występ chóru, grupy dziecięcej albo całego zespołu. Ostateczny program i skład ustalamy wspólnie, zależnie od terminu oraz dostępności członków.",
  "offer.primaryCta": "Poznaj ofertę występów",
  "offer.secondaryCta": "Zapytaj o dostępność",
  "offer.emailSubject": "Zapytanie o dostępność zespołu",
  "offer.imageAlt": "Wszystkie grupy Zespołu Pieśni i Tańca Halka na scenie",
  "history.eyebrow": "Historia, która nadal trwa",
  "history.start": "1948",
  "history.now": "Dziś",
  "history.title": "Od 1948 roku",
  "history.titleAccent": "tańczymy razem.",
  "history.lead": "Zmieniały się pokolenia, sceny i repertuar. Halka pozostała miejscem, w którym pieśni i tańce są przekazywane dalej — nie jako zamknięte archiwum, lecz żywa część wspólnego życia.",
  "history.fact1Value": "75+",
  "history.fact1Label": "lat działalności",
  "history.fact2Value": "4",
  "history.fact2Label": "działające grupy",
  "history.factsLabel": "Halka w liczbach",
  "history.visualLabel": "Halka dawniej i dziś",
  "history.oldImageAlt": "Archiwalne zdjęcie pierwszego składu Zespołu Pieśni i Tańca Halka z 1948 roku",
  "history.oldImageLabel": "Kiedyś · 1948",
  "history.oldImageCaption": "Pierwszy skład Halki",
  "history.nowImageAlt": "Współczesny skład Zespołu Pieśni i Tańca Halka",
  "history.nowImageCaption": "Kolejne pokolenia na jednej scenie",
  "costumes.eyebrow": "Różne regiony · jedna kolekcja",
  "costumes.title": "Kostium",
  "costumes.titleAccent": "opowiada zanim zacznie się taniec",
  "costumes.lead": "Każdy haft, pas i sposób wiązania ma własne znaczenie. Poznaj stroje, w których Halka prezentuje różnorodność polskich regionów — nie tylko jako kolekcję, ale część scenicznej opowieści.",
  "costumes.cta": "Odkryj kostiumy",
  "costumes.mosaicLabel": "Detale kostiumów scenicznych Halki",
  "costumes.tile1Alt": "Zdobiony skórzany pas stroju Górali Żywieckich",
  "costumes.tile1Caption": "Pas góralski",
  "costumes.tile2Alt": "Kwiatowy haft kobiecego stroju Górali Żywieckich",
  "costumes.tile2Caption": "Haft żywiecki",
  "costumes.tile3Alt": "Wielobarwne wstążki kobiecego stroju lubelskiego",
  "costumes.tile3Caption": "Wstążki",
  "costumes.tile4Alt": "Haftowany granatowy kaftan stroju Krakowiaków Zachodnich",
  "costumes.tile4Caption": "Haft krakowski",
  "costumes.tile5Alt": "Haftowany kołnierz i korale kobiecego stroju lubelskiego",
  "costumes.tile5Caption": "Kołnierz",
  "contact.eyebrow": "Porozmawiajmy",
  "contact.title": "Kontakt",
  "contact.lead": "Chcesz dołączyć, zaprosić Halkę albo zapytać o współpracę? Wybierz najwygodniejszy kontakt.",
  "contact.emailLabel": "Napisz do nas",
  "contact.phoneLabel": "Zadzwoń",
  "contact.addressLabel": "Siedziba zespołu",
  "contact.krsLabel": "KRS",
  "contact.nipLabel": "NIP",
  "social.title": "Bądź bliżej Halki.",
  "social.lead": "Obserwuj nas i zaglądaj za kulisy. Zobacz, co dzieje się na próbach, i nie przegap kolejnego koncertu.",
  "social.facebookTitle": "Obserwuj na Facebooku",
  "social.facebookText": "Zapowiedzi koncertów i aktualności",
  "social.instagramTitle": "Obserwuj na Instagramie",
  "social.instagramText": "Próby, kulisy i chwile ze sceny",
  "social.youtubeTitle": "YouTube",
  "social.youtubeText": "Występy i nagrania",
  "social.hint": "Przejdź na nasz profil i kliknij „Obserwuj”.",
  "social.ariaLabel": "Media społecznościowe Halki",
};

export const historyCopyDefaults: CopyMap = {
  "meta.title": "Historia Zespołu Halka | Od 1948 roku",
  "meta.description": "Poznaj najważniejsze momenty w historii Zespołu Pieśni i Tańca Halka z Lublińca — od założenia w 1948 roku po współczesność.",
  "skipLabel": "Przejdź do historii",
  "hero.eyebrow": "Historia Zespołu Halka",
  "hero.title": "Od 1948 roku",
  "hero.titleAccent": "tańczymy razem.",
  "hero.lead": "Zmieniały się pokolenia, sceny i repertuar. Niezmienna została potrzeba wspólnego śpiewu, ruchu i przekazywania tradycji dalej.",
  "hero.cta": "Przejdź do osi czasu",
  "hero.imageAlt": "Współczesny skład Zespołu Pieśni i Tańca Halka",
  "hero.imageLabel": "Halka dzisiaj",
  "hero.imageCaption": "Pieśń. Taniec. Pokolenia.",
  "opening.eyebrow": "Początek opowieści",
  "opening.title": "Zaczęło się od ludzi, którzy chcieli śpiewać.",
  "opening.text": "W 1948 roku Józef Kościelny i grono przyjaciół powołali zespół, aby ożywić życie śpiewacze Lublińca i pielęgnować regionalne tradycje. Od tamtej pory Halka pozostaje wspólnotą, w której doświadczenie jednego pokolenia staje się początkiem następnego.",
  "opening.fact1Label": "rok założenia",
  "opening.fact2Label": "działające grupy",
  "opening.fact3Label": "lat wspólnej historii",
  "opening.factsLabel": "Halka w liczbach",
  "timeline.eyebrow": "02 · Najważniejsze momenty",
  "timeline.title": "Historia w sześciu krokach.",
  "timeline.lead": "To początek kroniki. Będziemy ją rozwijać wraz z kolejnymi potwierdzonymi materiałami i archiwalnymi fotografiami.",
  "timeline.source": "Historia opracowana na podstawie materiałów zespołu oraz Miejskiego Domu Kultury w Lublińcu.",
  "generations.visualLabel": "Halka — kolejne pokolenia",
  "generations.mainAlt": "Tancerze Halki podczas wspólnego układu",
  "generations.smallAlt": "Najmłodsi członkowie Zespołu Halka",
  "generations.smallCaption": "Następne pokolenie",
  "generations.eyebrow": "03 · Historia trwa",
  "generations.title": "Tradycja żyje tylko wtedy, gdy jest przekazywana dalej.",
  "generations.text": "Dziś Halkę tworzą dzieci, młodzież i dorośli. Każda grupa pracuje we własnym rytmie, ale wszystkie spotykają się w jednej opowieści i na jednej scenie.",
  "generations.cta": "Poznaj grupy i dołącz",
  "generations.groupsLabel": "Działające grupy zespołu",
  "next.eyebrow": "Opowieść trwa",
  "next.title": "Zobacz Halkę na scenie.",
  "next.eventsCta": "Najbliższe wydarzenia",
  "next.galleryCta": "Przejdź do galerii",
};

export const costumesCopyDefaults: CopyMap = {
  "meta.title": "Kostiumy zespołu | Halka Lubliniec",
  "meta.description": "Poznaj kostiumy Zespołu Pieśni i Tańca Halka z Lublińca: sylwetki, hafty, koronki, dodatki i strój w ruchu.",
  "hero.eyebrow": "Kostiumy sceniczne",
  "hero.title": "Poznaj nasze",
  "hero.titleAccent": "stroje.",
  "hero.lead": "Każdy region opowiada własną historię kolorem, krojem i detalem. Zobacz kostiumy Halki z bliska — w pełnych sylwetkach i najdrobniejszych zdobieniach.",
  "hero.primaryCta": "Sprawdź stroje",
  "hero.secondaryCta": "Zobacz detale",
  "hero.imageAlt": "Tancerka Halki w stroju ludowym",
  "intro.title": "Nie tylko ubiór.",
  "intro.titleAccent": "Część opowieści.",
  "intro.text": "Kostium porządkuje obraz zespołu, podkreśla gest i pozwala rozpoznać charakter scenicznej opowieści. To, co z widowni tworzy jedną barwną całość, z bliska okazuje się kompozycją wielu warstw.",
  "intro.layerTitle": "Warstwy",
  "intro.layerText": "forma i proporcja",
  "intro.colorTitle": "Kolor",
  "intro.colorText": "rytm i kontrast",
  "intro.motionTitle": "Ruch",
  "intro.motionText": "kostium na scenie",
  "catalogue.eyebrow": "Kolekcja Halki",
  "catalogue.title": "Wybierz region.",
  "catalogue.lead": "Najpierw wybierz stroje damskie lub męskie, potem otwórz region i zobacz pełne sylwetki oraz detale.",
  "catalogue.female": "Stroje damskie",
  "catalogue.male": "Stroje męskie",
  "catalogue.open": "Otwórz prezentację",
  "catalogue.typeLabel": "Rodzaj stroju",
  "catalogue.categoriesLabel": "Kategorie kostiumów",
  "modal.female": "Strój damski",
  "modal.male": "Strój męski",
  "modal.close": "Zamknij prezentację stroju",
  "modal.previous": "Poprzednie zdjęcie",
  "modal.next": "Następne zdjęcie",
  "modal.versionLabel": "Wersja stroju",
  "modal.photosLabel": "zdjęć",
  "modal.showPhoto": "Pokaż zdjęcie",
  "details.title": "To detal buduje całość.",
};

export const eventsCopyDefaults: CopyMap = {
  "meta.title": "Wydarzenia i próby | ZPiT Halka Lubliniec",
  "meta.description": "Kalendarz występów, warsztatów i regularnych prób Zespołu Pieśni i Tańca Halka z Lublińca.",
  "skipLabel": "Przejdź do wydarzeń",
  "hero.eyebrow": "Kalendarz",
  "hero.title": "Zobacz nas",
  "hero.titleAccent": "na żywo.",
  "hero.lead": "Występy, warsztaty i stały plan prób — wszystkie terminy, których naprawdę potrzebujesz, w jednym miejscu.",
  "hero.primaryCta": "Najbliższe wydarzenia",
  "hero.secondaryCta": "Sprawdź próby",
  "hero.imageAlt": "Tancerze Halki podczas Tygodnia Kultury Beskidzkiej",
  "timeUnknown": "Godzina zostanie podana",
  "upcoming.eyebrow": "Najbliższe występy",
  "upcoming.title": "Gdzie nas zobaczysz.",
  "upcoming.emptyTitle": "Czekamy na potwierdzenie terminów.",
  "upcoming.emptyText": "Nowe występy pojawią się tutaj, gdy tylko zostaną ustalone.",
  "calendar.eyebrow": "Pełny terminarz",
  "calendar.title": "Wybierz miesiąc.",
  "calendar.lead": "Wybierz miesiąc, aby sprawdzić występy, warsztaty i regularne próby.",
  "calendar.empty": "W tym miesiącu nie ma jeszcze opublikowanych wydarzeń.",
  "calendar.months": "Styczeń|Luty|Marzec|Kwiecień|Maj|Czerwiec|Lipiec|Sierpień|Wrzesień|Październik|Listopad|Grudzień",
  "calendar.weekdays": "Pon|Wt|Śr|Czw|Pt|Sob|Nie",
  "calendar.selectMonthLabel": "Wybierz miesiąc",
  "calendar.performingGroupsLabel": "Występujące grupy",
  "calendar.practiceNote": "Regularne próby ({count}) są zaznaczone w kalendarzu. Ich stałe godziny znajdziesz poniżej.",
  "archive.label": "Archiwum {year}",
  "archive.title": "Minione wydarzenia",
  "archive.action": "Pokaż listę",
  "practices.eyebrow": "Stały plan",
  "practices.title": "Próby w Lublińcu.",
  "practices.lead": "Wszystkie grupy spotykają się w siedzibie zespołu przy ul. Stalmacha 12.",
  "practices.mapCta": "Pokaż siedzibę na mapie",
  "practices.groupCta": "Informacje o grupie",
  "cta.eyebrow": "Organizujesz wydarzenie?",
  "cta.title": "Halka może wystąpić także u Ciebie.",
  "cta.label": "Poznaj ofertę",
};

export const galleryUiCopyDefaults: CopyMap = {
  "meta.title": "Galeria zespołu | Halka Lubliniec",
  "meta.description": "Galerie z koncertów, warsztatów, wyjazdów i spotkań Zespołu Pieśni i Tańca Halka z Lublińca.",
  "results.one": "1 galeria",
  "results.many": "{count} galerii",
  "card.cta": "Zobacz zdjęcia",
  "card.openLabel": "Otwórz galerię",
  "lightbox.close": "Zamknij galerię",
  "lightbox.previous": "Poprzednie zdjęcie",
  "lightbox.next": "Następne zdjęcie",
  "lightbox.place": "Miejsce",
  "lightbox.photos": "Zdjęcia",
  "lightbox.author": "Autor",
  "lightbox.hint": "Użyj strzałek klawiatury lub przycisków na zdjęciu.",
  "filter.label": "Filtruj galerię według roku",
  "lightbox.choosePhoto": "Wybierz zdjęcie",
};

export const joinUiCopyDefaults: CopyMap = {
  "meta.title": "Dołącz do Halki | ZPiT Halka Lubliniec",
  "meta.description": "Nabór do czterech grup Zespołu Pieśni i Tańca Halka trwa przez cały rok. Zajęcia są bezpłatne, bez przesłuchań i bez wymaganego doświadczenia.",
  "schedule.fixed": "Stały termin",
  "schedule.next": "Najbliższe próby",
  "schedule.location": "Siedziba zespołu",
  "map.title": "Mapa z siedzibą Zespołu Pieśni i Tańca Halka w Lublińcu",
  "hero.noteLabel": "Najważniejsze informacje o dołączeniu do zespołu",
};

export const inviteUiCopyDefaults: CopyMap = {
  "meta.title": "Zaproś Halkę na wydarzenie | ZPiT Halka Lubliniec",
  "meta.description": "Poznaj gotowe suity i możliwe formaty występu Zespołu Pieśni i Tańca Halka. Zapytaj o dostępność zespołu i wspólnie ustal program wydarzenia.",
  "skipLabel": "Przejdź do treści",
  "hero.title": "Zaproś Halkę.",
  "hero.titleAccent": "Niech scena ożyje.",
  "hero.primaryCta": "Sprawdź dostępność",
  "hero.phoneLabel": "Skontaktuj się!",
  "hero.imageAlt": "Tancerze Halki podczas wydarzenia plenerowego",
  "hero.note": "Żeby sprawdzić termin, wystarczą 3 informacje",
  "hero.noteLabel": "Najważniejsze informacje potrzebne do sprawdzenia terminu",
  "hero.fact1Title": "Termin",
  "hero.fact1Text": "data wydarzenia",
  "hero.fact2Title": "Miejsce",
  "hero.fact2Text": "miasto i rodzaj sceny",
  "hero.fact3Title": "Format",
  "hero.fact3Text": "planowany czas występu",
  "formats.image1Alt": "Para taneczna Halki podczas suity śląskiej",
  "formats.image2Alt": "Męska część chóru Halki podczas występu",
  "formats.image3Alt": "Wszystkie pokolenia Halki na jednej scenie",
  "formats.title": "Trzy sposoby,",
  "formats.titleAccent": "żeby spotkać Halkę.",
  "suites.title": "Trzy regiony.",
  "suites.titleAccent": "Trzy sceniczne temperamenty.",
  "process.eyebrow": "Od wiadomości do występu",
  "process.title": "Prosto i bez niedomówień.",
  "contact.title": "Zróbmy razem",
  "contact.titleAccent": "dobry występ.",
  "contact.emailLabel": "Napisz e-mail",
  "contact.phoneLabel": "Zadzwoń",
  "process.imageAlt": "Tancerze Halki ćwiczący w parach podczas warsztatów w Wiśle",
  "social.messengerLabel": "Messenger",
  "social.instagramLabel": "Instagram",
  "booking.subject": "Zapytanie o występ ZPiT Halka",
  "booking.body": "Dzień dobry,\n\nchcę zaprosić ZPiT Halka na wydarzenie.\n\nTermin:\nMiejsce:\nRodzaj wydarzenia:\nPrzewidywana długość występu:\n\nProszę o informację o dostępności i możliwym programie.",
};

export const heroVariantsCopyDefaults: CopyMap = {
  ...homeCopyDefaults,
  "meta.title": "Wariant hero | Halka Lubliniec",
  "header.label": "Dopracowany kierunek hero",
  "header.return": "Strona główna",
  "header.brand": "HALKA",
  "header.city": "Lubliniec",
  "after.eyebrow": "Wir tradycji",
  "after.title": "Rozpoznawalny ruch. Nowy pierwszy ekran.",
  "after.lead": "Duży kolisty kadr wraca ze starej strony. Geometria ornamentu łączy hero z galerią i kostiumami.",
  "after.point1Title": "Najpierw człowiek",
  "after.point1Text": "Zdjęcie pozostaje czyste i czytelne, bez maski rozmywającej jego charakter.",
  "after.point2Title": "Folklor w detalu",
  "after.point2Text": "Drobne romby i rytm linii wspierają kompozycję, zamiast konkurować z nią.",
  "after.point3Title": "Ruch ze scrollem",
  "after.point3Text": "Rozety podążają za przewijaniem, a hero respektuje ograniczenie animacji.",
};
