import { defineField, defineType } from "sanity";

export const invitePage = defineType({
  name: "invitePage",
  title: "Zaproś Halkę",
  type: "document",
  groups: [
    { name: "hero", title: "Pierwszy ekran" },
    { name: "formats", title: "Formaty występu" },
    { name: "suites", title: "Suity" },
    { name: "process", title: "Ustalenia" },
    { name: "stage", title: "Galeria" },
    { name: "contact", title: "Kontakt" },
  ],
  fields: [
    defineField({
      name: "hero",
      title: "Pierwszy ekran",
      type: "object",
      group: "hero",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Początek nagłówka", type: "string" }),
        defineField({ name: "titleAccent", title: "Czerwony fragment", type: "string" }),
        defineField({ name: "titleSuffix", title: "Końcówka nagłówka", type: "string" }),
        defineField({ name: "lead", title: "Wprowadzenie", type: "text", rows: 4 }),
        defineField({ name: "primaryCtaLabel", title: "Główny przycisk", type: "string" }),
        defineField({ name: "secondaryCtaLabel", title: "Drugi przycisk", type: "string" }),
        defineField({ name: "image", title: "Zdjęcie", type: "cmsImage" }),
        defineField({ name: "noteLabel", title: "Etykieta notatki", type: "string" }),
        defineField({ name: "noteText", title: "Notatka na zdjęciu", type: "text", rows: 2 }),
      ],
    }),
    defineField({
      name: "formats",
      title: "Formaty występu",
      type: "object",
      group: "formats",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Nagłówek", type: "string" }),
        defineField({ name: "titleAccent", title: "Druga część nagłówka", type: "string" }),
        defineField({ name: "lead", title: "Wprowadzenie", type: "text", rows: 3 }),
        defineField({ name: "items", title: "Możliwe formaty", description: "Przeciągnij elementy, aby zmienić ich kolejność.", type: "array", of: [{ type: "iconTextItem" }], validation: (rule) => rule.max(4) }),
      ],
    }),
    defineField({
      name: "suites",
      title: "Suity",
      type: "object",
      group: "suites",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Nagłówek", type: "string" }),
        defineField({ name: "titleAccent", title: "Druga część nagłówka", type: "string" }),
        defineField({ name: "lead", title: "Wprowadzenie", type: "text", rows: 3 }),
        defineField({ name: "items", title: "Gotowe suity", description: "Przeciągnij elementy, aby zmienić ich kolejność.", type: "array", of: [{ type: "suiteItem" }] }),
        defineField({ name: "costumesCtaLabel", title: "Odnośnik do kostiumów", type: "string" }),
      ],
    }),
    defineField({
      name: "process",
      title: "Ustalenia przed występem",
      type: "object",
      group: "process",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Nagłówek", type: "string" }),
        defineField({ name: "image", title: "Zdjęcie", type: "cmsImage" }),
        defineField({ name: "items", title: "Co ustalamy", type: "array", of: [{ type: "iconTextItem" }], validation: (rule) => rule.max(4) }),
      ],
    }),
    defineField({
      name: "stage",
      title: "Zajawka galerii",
      type: "object",
      group: "stage",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Nagłówek", type: "string" }),
        defineField({ name: "titleAccent", title: "Wyróżniony fragment", type: "string" }),
        defineField({ name: "lead", title: "Wprowadzenie", type: "text", rows: 2 }),
        defineField({ name: "image", title: "Zdjęcie", type: "cmsImage" }),
        defineField({ name: "eventTitle", title: "Nazwa wydarzenia", type: "string" }),
        defineField({ name: "eventText", title: "Opis zdjęcia", type: "string" }),
        defineField({ name: "ctaLabel", title: "Odnośnik do galerii", type: "string" }),
      ],
    }),
    defineField({
      name: "contact",
      title: "Kontakt",
      type: "object",
      group: "contact",
      fields: [
        defineField({ name: "eyebrow", title: "Mały nagłówek", type: "string" }),
        defineField({ name: "title", title: "Nagłówek", type: "string" }),
        defineField({ name: "lead", title: "Wprowadzenie", type: "text", rows: 2 }),
        defineField({ name: "hint", title: "Podpowiedź do wiadomości", type: "text", rows: 2 }),
        defineField({ name: "socialPrompt", title: "Tekst nad social mediami", type: "string" }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Zaproś Halkę", subtitle: "Treść podstrony /zapros-halke" }) },
});

